from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#Django rest framework
from rest_framework import routers, serializers, viewsets
from dmt.viewsets import *
from cireports.viewsets import *
from depmodel.viewsets import *
from django.views.generic import TemplateView
from django.conf.urls.static import static
from angularVis.views import BaselineView
from angularVis.views import getLatestENMDrop
from dmt.views import ServerUtilizationView
from django.contrib.auth.decorators import login_required
from fastcommit.viewsets import *
from virtual.viewsets import *
from foss.viewsets import *

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
#Deployment routers
router.register(r'deploymentbaseline',DeploymentBaselineViewSet)
router.register(r'deployment/clusters',ClusterViewSet)
router.register(r'deployment/testcases',DeploymentTestcaseViewSet)
router.register(r'deployment/testresults',MapTestResultsToDeploymentViewSet,base_name="testresults")
router.register(r'deployment/testgroups',TestGroupViewSet)
router.register(r'deployment/testgroup/mapping',MapTestGroupToDeploymentViewSet)
router.register(r'api/product',ISOBuildViewSet)
router.register(r'api/cifwk/config/section/',CifwkConfigViewSet,base_name="cifwkconfig")
router.register(r'getVersionedPlugins',GetVersionedPluginsViewSet)

#FastCommit Routers
simple_router = routers.SimpleRouter(trailing_slash=False)
simple_router.register(r'fastcommit/images', DockerImageContentsViewSet)

# pENM Routers
urlpatterns = patterns('cireports',
    (r'^$', 'views.homepage'),
    (r'^releaseProducts/$', 'views.releaseProducts'),
    (r'^ps/$', 'views.prodSetSummary'),
    (r'^(\S+)/releases/$', 'views.releaseIndex'),
    (r'^(\S+)/prodSetReleases/$', 'views.prodSetRelIndex'),
    url(r'^(\S+)/content/(\S+)/$', 'views.displayProdSetContent', name='displayLatestProdSetContent'),
    url(r'^(\S+)/content/(\S+)/(\S+)$', 'views.displayProdSetContent', name='displayProdSetContentVersion'),
    (r'^(\S+)/historicalContent/(\S+)$', 'views.displayProdSetVersions'),
    (r'^(\S+)/dropMedia/(\S+)/createversion/$', 'views.createProductSetVersion'),
    (r'^(\S+)/dropMedia/(\S+)/(\S+)/xml/$', 'views.dropMediaStatus'),
    (r'^(\S+)/dropMedia/(\S+)/$', 'views.displayDropMedia'),
    (r'^(\S+)/(\S+)/obsoleteMediaVersion/$', 'views.obsoleteMedia'),
    (r'^(\S+)/(\S+)/obsoleteMediaHistory/$', 'views.obsoleteMediaHistory'),
    (r'^(\S+)/drop/(\S+)/latestCDB/$', 'views.latestCDBIndex'),
    (r'^(\S+)/drop/(\S+)/latestCDB/(\S+)/cdbxml/$', 'views.dropCDBStatus'),
    (r'^(\S+)/drop/(\S+)/latestCDB/(\S+)/xml/$', 'views.displayLatestCDB'),
    (r'^(\S+)/(\S+)/CDBsummary/$', 'views.displayCDBsummary'),
    (r'^(\S+)/(\S+)/PSsummary/$', 'views.displayPSsummary'),
    (r'^(\S+)/drops/(\S+)/obsoleteVersion/$', 'views.obsolete'),
    (r'^(\S+)/drops/(\S+)/obsoleteInfo/', 'views.obsoleteHistory'),
    (r'^(\S+)/drops/(\S+)/(\S+)/json/$', 'views.dropStatus'),
    (r'^(\S+)/drops/(\S+)/cdbxml/$', 'views.dropCDBStatus'),
    (r'^(\S+)/drops/$', 'views.dropIndex'),
    (r'^(\S+)/drops/(\S+)/historic/(\S+)/(\S+)/$', 'views.displayCDBContent'),
    (r'^(\S+)/drops/(\S+)/historic/$', 'views.displayCDBHistory'),
    (r'^(\S+)/drops/(\S+)/$', 'views.displayDrop'),
    (r'^(\S+)/packages/$', 'views.packageIndex'),
    (r'^(\S+)/packages/(\S+)/xml/$', 'views.packageVersionsStatus'),
    (r'^(\S+)/packages/(\S+)/buildxml/$', 'views.packageBuildStatus'),
    (r'^cloudnative/getCloudNativeImageContent/(\S+)/(\S+)/$', 'views.getCloudNativeImageContent'),
    (r'^cloudnative/getCloudNativeHelmRevision/(\S+)/(\S+)/(\S+)/$', 'views.getCloudNativeHelmRevision'),
    (r'^cloudnative/getCloudNativeProductSetContent/(\S+)/(\S+)/$', 'views.getCloudNativeProductSetContent'),
    (r'^(\S+)/(\S+)/showPackageDependencies', 'views.showPackageDependencies'),
    (r'^(\S+)/(\S+)/dependencyMapping/(\S+)/', 'views.packageDependencyMappings'),
    (r'^(\S+)/(\S+)/(\S+)/deleteDependencyMapping/', 'views.deleteDependencyMapping'),
    (r'packages/(\S+)/xml/$', 'views.packageVersionsStatus'),
    (r'packages/(\S+)/json/$', 'views.packageVersionsStatusJson'),
    (r'^(\S+)/packages/(\S+)/$', 'views.displayPackage'),
    (r'^packagesInProduct/$', 'views.getPackagesDeliveredToProduct'),
    (r'^artifactsInProduct/$', 'views.getArtifactsDeliveredToProduct'),
    (r'^(\S+)/solutionsets/(\S+)/(\S+)/xml/$', 'views.solutionSetRevisionStatus'),
    (r'^(\S+)/solutionsets/(\S+)/xml/$', 'views.solutionSetStatus'),
    (r'^(\S+)/solutionsets/(\S+)/(\S+)/$', 'views.displaySolutionSetRevision'),
    (r'^(\S+)/solutionsets/(\S+)/$', 'views.displaySolutionSet'),
    (r'^(\S+)/solutionsets/$', 'views.solutionSetIndex'),
    (r'^(\S+)/admin/deliver/$', 'admin_views.deliver'),
    (r'^(\S+)/delivery/(\S+)/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.makeNewPackageDelivery'),
    (r'^cifwkPackageImport/$', 'views.restImportPackageToCiFwk'),
    (r'^cifwkTestwareImport/$', 'views.restImportTestwareToCiFwk'),
    (r'^getVersionFromRstate/$','views.getVersionFromRstate'),
    (r'^getRStateFromVersion/$','views.getRStateFromVersion'),
    (r'^getRStateFromPRIM/$','views.getlatestCXPRStatePRIM'),
    (r'^deliverToDrop/$', 'views.makeRestDeliveryToDrop'),
    (r'^obsoletePackageCIFWK/$', 'views.restObsoletePackageCIFWK'),
    (r'^obsoleteMediaCIFWK/$', 'views.restObsoleteMediaArtifactCIFWK'),
    (r'^createISOcontentOnly/$', 'views.restISOcontentOnly'),
    (r'^createISOContent/$', 'views.createISOContent'),
    (r'^deleteISOcontentOnly/$', 'views.restDeleteISOcontentOnly'),
    (r'^(\S+)/delivery/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.makeDelivery'),
    (r'^(\S+)/doDelivery/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.makeDelivery'),
    (r'^(\S+)/pri/(\S+)/$', 'views.viewPRI'),
    (r'^(\S+)/pri/(\S+)/(\S+)/(\S+)/(\S+)', 'views.viewPRI'),
    (r'^testware/getmapping/$', 'views.returnTestwareMap'),
    (r'^testware/createpom/$', 'views.returnTestwarePom'),
    (r'^testware/gettestware/$', 'views.returnTestware'),
    (r'^testware/getmappedtestware/$', 'views.returnMappedTestware'),
    (r'^(\S+)/testware/$', 'views.displayTestware'),
    (r'^(\S+)/testware/xml/$', 'views.displayTestwareArtifacts'),
    (r'^getLatestTestware/$', 'views.getAllLatestTestwareArtifacts'),
    (r'^(\S+)/unmappedtestware/$', 'views.displayUnMappedTestware'),
    (r'^(\S+)/unmappedtestware/xml/$', 'views.displayUnMappedTestwareArtifacts'),
    (r'^(\S+)/testware/mapping/(\S+)/$', 'views.viewTestwareMapping'),
    (r'^(\S+)/testware/deletemapping/(\S+)/$', 'views.deleteTestwareMapping'),
    (r'^(\S+)/testware/(\S+)/deletemapping/(\S+)/$', 'views.deleteTWMapping'),
    (r'^(\S+)/testware/mapping/$', 'views.mapTestware'),
    (r'^(\S+)/testware/artifacts/$', 'views.generateTestwareArtifacts'),
    (r'^(\S+)/testware/showall/(\S+)/xml/$', 'views.displayTestwareVersions'),
    (r'^(\S+)/testware/showall/(\S+)/$', 'views.showTestwareVersionsAll'),
    (r'^(\S+)/testware/changeStatus/(\S+)/$', 'views.testwareStatus'),
    (r'^(\S+)/testware/obsolete/(\S+)/$', 'views.obsoleteTestware'),
    (r'^(\S+)/testware/reactivate/(\S+)/$', 'views.reactivateTestware'),
    (r'^(\S+)/returnresults/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.returnTestRunResult'),
    (r'^returnreport/(\S+)/$', 'views.returnTestRunReport'),
    (r'^(\S+)/(\S+)/(\S+)/(\S+)/returnKGBreadyDetails/(\S+)/$', 'views.returnKGBreadyDetails'),
    (r'^(\S+)/(\S+)/(\S+)/(\S+)/returnCautionStatusDetails/(\S+)/$', 'views.returnCautionStatusDetails'),
    (r'^(\S+)/(\S+)/(\S+)/(\S+)/returnisoreport/(\S+)/$', 'views.returnTestRun'),
    (r'^radiator/$', 'vis.radiator'),
    (r'^radiator/view/(.*)/([0-9]+.[0-9]+.[0-9]+)/$', 'vis.radiator'),
    (r'^(\S+)/nextdrop/json/$', 'vis.nextDrop'),
    (r'^mediaDelivery/(\S+)/(\S+)/$', 'views.makeNewMediaDelivery'),
    (r'^mediaDeliveryProductSet/(\S+)/(\S+)/(\S+)/$', 'views.makeMediaDelivery'),
    (r'^mediaDeliveryToDrop/$', 'views.restDeliveryMediaArtifactToProductSet'),
    (r'^mediaDeliveryToDrop/(\S+)/$', 'views.restDeliveryMediaArtifactToProductSet'),
    (r'^(\S+)/media/(\S+)/(\S+)/$', 'views.displayMediaByRelease'),
    (r'^(\S+)/(\S+)/media/$', 'views.displayMediaByDrop'),
    (r'^(\S+)/(\S+)/mediaContent/(\S+)/(\S+)/$', 'views.displayMediaContent'),
    (r'^(\S+)/(\S+)/mediaContentJson/(\S+)/(\S+)/(\S+)/$', 'views.getMediaContent'),
    (r'^(\S+)/(\S+)/setCautionStatus/(\S+)/(\S+)/$', 'views.setCautionStatus'),
    (r'^(\S+)/media/$', 'views.mediaIndex'),
    (r'^(\S+)/primOptions/$', 'views.primOptions'),
    (r'^(\S+)/(\S+)/primCXP/$', 'views.primCXP'),
    (r'^(\S+)/(\S+)/doprimCXP/$', 'views.primCXP'),
    (r'^(\S+)/(\S+)/primCXPupdate/$', 'views.updatePrimCXP'),
    (r'^(\S+)/(\S+)/prim/$', 'views.prim'),
    (r'^(\S+)/(\S+)/doprim/$', 'views.prim'),
    (r'^primUpdate/$', 'views.updatePrim'),
    (r'^(\S+)/documents/(\S+)/$', 'views.displayDocuments'),
    (r'^(\S+)/addDocument/(\S+)/$', 'views.addDocument'),
    (r'^(\S+)/(\S+)/(\S+)/editDocument/', 'views.editDocument'),
    (r'^(\S+)/(\S+)/(\S+)/deleteDocument/', 'views.deleteDocument'),
    (r'^cireports/new_product_delivery/$,', 'views.makeNewPackageDelivery'),
    (r'^(\S+)/(\S+)/GATinformation/$', 'views.displayGAT'),
    (r'^cireports/allPackages/', 'views.allPackages'),
    (r'^cireports/allArtifacts/', 'views.allArtifacts'),
    (r'^(\S+)/isoVersionList/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.isoVersionList'),
    (r'^(\S+)/cireports/updateNodePRIStatus/(\S+)/$', 'views.updateNodePRIStatus'),
    (r'^(\S+)/(\S+)/GenerateNodePRI/$', 'views.generateNodePRI'),
    (r'^getKGBPackageDenpencies/$','views.getKGBPackageDenpencies'),
    (r'^getlatestiso/$','views.getLatestIso'),
    (r'^getlatestisover/$','views.getLatestIsoVer'),
    (r'^upload/$','views.uploadFile'),
    (r'^(\S+)/deliver_info/(\S+)/(\S+)/(\S+)$','views.pkgDeliveryData'),
    (r'^CIFWKMediaImport/$','views.restCIFWKMediaImport'),
    (r'^(\S+)/(\S+)/returnpsreport/(\S+)/$', 'views.returnPSTestRun'),
    (r'^productsetcdbstatus/(\S+)/(\S+)/$', 'views.productSetCDBStatus'),
    (r'^(\S+)/(\S+)/(\S+)/returnProdSetKGBreadyDetails/(\S+)/$', 'views.returnProdSetKGBreadyDetails'),
    (r'^(\S+)/(\S+)/(\S+)/returnProdSetCautionStatusDetails/(\S+)/$', 'views.returnProdSetCautionStatusDetails'),
    (r'^getMediaArtifactNumber/$', 'views.getMediaArtifactNumber'),
    (r'^getMediaArtifactGroup/$', 'views.getMediaArtifactGroup'),
    (r'^getMediaArtifactVersions/$', 'views.getMediaArtifactVersions'),
    (r'^getProductSetNumber/$', 'views.getProductSetNumber'),
    (r'^getProductSetVersions/$', 'views.getProductSetVersions'),
    (r'^getLastGoodProductSetVersion/$', 'views.getLastGoodProductSetVersion'),
    (r'^getLatestProductSetVersion/$', 'views.getLatestProductSetVersion'),
    (r'^getProductSetVersionContents/$', 'views.getProductSetVersionContents'),
    (r'^getDropContents/$', 'views.getDropContents'),
    (r'^checkForChanges/$', 'views.checkForChanges'),
    (r'^(\S+)/configureSummary/$', 'views.configureSummary'),
    (r'^(\S+)/imageContent/(\S+)/(\S+)$', 'views.displayImageContent'),
    url(r'^(\S+)/deliver_info/(\S+)/$','views.deliveryData', name='deliver_release_stats'),
    url(r'^(\S+)/deliver_info/(\S+)/(\S+)$','views.deliveryData', name='deliver_drop_stats'),
    url(r'^(\S+)/full_deliver_info/(\S+)/(\S+)/(\S+)$','views.deliveryData', name='deliver_full_stats'),
    url(r'^(\S+)/deliver_stats/(\S+)/(\S+)/(\S+)/xml$','views.displayDeliveryStats'),
    url(r'^(\S+)/full_deliver_stats/(\S+)/(\S+)/(\S+)/(\S+)/xml$','views.displayDeliveryStats'),
    (r'^(\S+)/viewComponentEntryPoint/$', 'views.viewComponentEntryPoint'),
    (r'^(\S+)/getHighLevelComponents/.json/$', 'views.getHighLevelComponents'),
    (r'^childComponentsInParentComponent/$', 'views.getLowLevelComponents'),
    (r'^(\S+)/importComponents/$', 'views.importComponents'),
    (r'^(\S+)/removeComponents/$', 'views.removeComponents'),
    (r'^packagesInComponent/$', 'views.packagesInComponent'),
    (r'^(\S+)/getProductLabels/.json/$', 'views.getProductLabels'),
    (r'^(\S+)/(\S+)/getParentComponentsOfLabel/.json/$', 'views.getParentComponentsOfLabel'),
    (r'^(\S+)/(\S+)/getChildLabelFromParentLabel/.json/$', 'views.getChildLabelFromParentLabel'),
    (r'^(\S+)/getComponentInformation/$', 'views.getComponentInformation'),
    (r'^getInfrastructurePackages/$', 'views.getInfrastructurePackages'),
    (r'^getArtifactFromLocalNexus/$', 'views.getArtifactFromLocalNexus'),
    (r'^getInfraFromIso/$', 'views.getInfrastructurePackagesFromIso'),
    (r'^updateInfraStatusOnPkg/$', 'views.updateInfraStatusOnPkg'),
    (r'^validateIsoUploadToHub/$', 'views.validateIsoUploadedToHub'),
    (r'^getArtifactsForTest/$', 'views.getArtifactsForTest'),
    (r'^getPrimData/$', 'views.getPrimDataForTest'),
    (r'^getISOContentDelta/$', 'views.getISOContentDelta'),
    (r'^compareCENMDiff/$', 'views.getCENMISODiff'),
    (r'^compareCENMISOsResult/$', 'views.getCENMISODiffResult'),
    (r'^compareISOs/$', 'views.getISODelta', {'bom' : False}),
    (r'^compareBOMs/$', 'views.getISODelta', {'bom' : True}),
    (r'^compareProductSets/$', 'views.getProductSetDelta'),
    (r'^(\S+)/(\S+)/compareISOs/$', 'views.getISODeltaInDrop', {'bom' : False}),
    (r'^(\S+)/(\S+)/compareBOMs/$', 'views.getISODeltaInDrop', {'bom' : True}),
    (r'^getAOMRstate/$', 'views.getAOMandRstateInfo'),
    (r'^getListOfPackages/$', 'views.getListOfPackages'),
    (r'^(\S+)/modifydrop/(\S+)/(\S+)/$', 'views.modifyDropReason'),
    (r'^(\S+)/modifydrop/(\S+)/$', 'views.modifyDrop'),
    (r'^createISOProductTestwareMapping/$', 'views.createISOProductTestwareMapping'),
    (r'^setDropStatus/$', 'views.setDropStatus'),
    (r'^getDropActivityHistory/$', 'views.getDropActivityHistory'),
    (r'^getPackagesInISO/$', 'views.getPackagesInISO'),
    (r'^setUserDetails/$', 'views.setUserDetails'),
    url(r'^(\S+)/queue/$','views.displayLatestQueue'),
    url(r'^(\S+)/queue/(\S+)/csv/$','views.displayDeliveryQueueCsv'),
    url(r'^(\S+)/queue/(\S+)/json/$','views.displayDeliveryQueueJson'),
    url(r'^(\S+)/queue/(\S+)/(\S+)/(\S+)/$','views.displayDeliveryQueue', name='successdQueue'),
    url(r'^(\S+)/queue/(\S+)/(\S+)/$','views.displayDeliveryQueue', name='idQueue'),
    url(r'^(\S+)/queue/(\S+)/$','views.displayDeliveryQueue', name='dQueue'),
    (r'^(\S+)/updateDeliveryGroup/(\S+)/(\S+)/(\S+)/$', 'views.updateDeliveryGroup'),
    (r'^(\S+)/deleteFromGroup/(\S+)/(\S+)/$', 'views.deleteDeliveryGroupItem'),
    (r'^(\S+)/deliverGroup/(\S+)/(\S+)/$', 'views.makeGroupDeliveries'),
    (r'^(\S+)/obsoleteGroup/(\S+)/(\S+)/$', 'views.obsoleteGroupDeliveries'),
    (r'^(\S+)/missingDependencies/(\S+)/(\S+)/$', 'views.setMissingDependenciesOnDeliveryGroup'),
    (r'^(\S+)/multipleDeliveries/$', 'views.makeDeliveryQueue'),
    (r'^getRevisionsOfPackage/$', 'views.getAllRevisionsOfAPackage'),
    (r'^addDeliveryGroup/$', 'views.addDeliveryGroup'),
    (r'^getActiveDrops/$', 'views.getActiveDropsInProduct'),
    (r'^(\S+)/addcomment/(\S+)/(\S+)/(\S+)/$','views.addDeliveryGroupComment'),
    (r'^(\S+)/deleteJiraFromGroup/(\S+)/(\S+)/$', 'views.deleteDeliveryGroupJira'),
    (r'^(\S+)/addjira/(\S+)/(\S+)/(\S+)/$','views.addDeliveryGroupJira'),
    (r'^(\S+)/drop/(\S+)/ISOdeliverygroups/$', 'views.getDropISODeliveryGroups'),
    url(r'^drops/(?P<drop_id>[0-9]+)/$', 'views.updateAutoDeliveryStatus'),
    (r'^(\S+)/ccbApproved/(\S+)/(\S+)/$', 'views.setCCBapprovedOnDeliveryGroup'),
    url(r'^api/productSet/(?P<productSet>.+)/activeDrops/$', GetActiveDropsInProductSet.as_view(), name="Get Active Drops in Product Set"),
    url(r'^api/productSet/(?P<productSet>.+)/drop/(?P<drop>.+)/mappings/$', GetDropMediaDeployContent.as_view(), name="Get Drop Deploy Mappings for Media Artifact"),
    url(r'^api/deliverygroup/subscriptions/$', login_required(DeliveryGroupSubscribeViewSet.as_view())),
    url(r'^api/product/(?P<productName>.+)/drop/(?P<dropName>.+)/isos/$', ISOBuildDropViewSet.as_view({'get':'list'})),
    url(r'^api/cifwk/config/section/(?P<section>.+)/option/(?P<option>.+)/', CifwkConfigViewSet.as_view(), name="cifwk_config_view"),
    url(r'^api/product/(?P<product>.+)/drop/(?P<drop>.+)/deliveryqueue/(?P<queueStatus>.+)/', DropDeliveryQueueArtifactsViewSet.as_view(), name="deliverytoPackageRevMappingView"),
    url(r'^api/product/(?P<product>.+)/createPackage/$', CreateProductPackageViewSet.as_view()),
    url(r'^api/product/(?P<product>.+)/drop/(?P<drop>.+)/(?P<type>.+)/versions/$', ISOBuildVersionsForDiffViewSet.as_view({'get':'list'})),
    url(r'^api/productSet/(?P<productSet>.+)/drop/(?P<dropName>.+)/versions/$', ProductSetVersionViewSet.as_view({'get':'list'})),
    url(r'^api/productSet/(?P<productSet>.+)/drop/(?P<dropName>.+)/versions/latest/$', ProductSetVersionLatestViewSet.as_view()),
    url(r'^api/productSet/(?P<productName>.+)/(?P<number>.+)/(?P<version>.+)/$', ProductSetVersionContentsSet.as_view({'get':'list'})),
    url(r'^api/getProductSetStatus/(?P<product>.+)/(?P<productset>.+)/$', GetProductSetStatus.as_view()),
    url(r'^api/aam/label/(?P<label>.+)/lookup/(?P<lookup>.+)/$', ArtifactAssociationViewSet.as_view(), name="Artifact Association"),
    url(r'^api/aam/product/(?P<product>.+)/label/(?P<label>.+)/lookup/(?P<lookup>.+)/$', ArtifactAssociationViewSet.as_view(), name="Artifact Association"),
    url(r'^api/product/(?P<product>.+)/getflow/$', ReturnFlowContext.as_view(), name="flow context"),
    url(r'^api/getflow/$', ReturnFlowContext.as_view(), name="flow context"),
    url(r'^api/getnotiniso/$', ReturnArtifactsNotInIso.as_view(), name="GetNotInIso"),
    url(r'^api/product/(?P<product>.+)/testwareartifacts/(?P<testwareartifacts>.+)/includedinprioritytestsuite/$', TestwareArtifactTestSuiteStatus.as_view(), name="Testware Artifact TestSuite"),
    url(r'^api/createDeliveryGroup/$', CreateDeliveryGroup.as_view()),
    url(r'^api/addTestCaseResult/$', AddTestCaseResult.as_view()),
    url(r'^api/getTestCaseResult/$', ReturnTestCaseResult.as_view()),
    url(r'^api/getartifactversiondata/artifact/(?P<artifactName>.+)/version/(?P<artifactVersion>.+)/$', GetArtifactVersionData.as_view(), name="Get Artifact Version Data"),
    url(r'^api/getreasonsfornokbgstatus/active/(?P<active>.+)$', GetActiveReasonsForNoKGBStatus.as_view(), name="Reasons for no KGB status on Artifact"),
    url(r'^api/deliveryGroup/(?P<deliveryGroup>.+)/artifact/(?P<artifactName>.+)/KGBresults/$', GetDeliveryGroupPackageRevKGB.as_view(), name="Frozen KGB Result for Artifact in a Delivery Group"),
    url(r'^api/deliveryGroup/(?P<deliveryGroup>.+)/KGBresults/$', GetDeliveryGroupPackageRevKGB.as_view(), name="Frozen KGB Results for Artifact(s) in a Delivery Group"),
    url(r'^api/product/(?P<product>.+)/drop/(?P<drop>.+)/artifact/(?P<artifactName>.+)/KGBresults/$', GetDropPackageRevKGB.as_view(), name="Frozen KGB Result for Artifact in a Drop"),
    url(r'^api/product/(?P<product>.+)/drop/(?P<drop>.+)/type/(?P<type>.+)/KGBresults/$', GetDropPackageRevKGB.as_view(), name="Frozen KGB Results for Artifact(s) Type:(packages or testware) in a Drop"),
    url(r'^api/product/(?P<product>.+)/drop/(?P<drop>.+)/KGBresults/$', GetDropPackageRevKGB.as_view(), name="Frozen KGB Results for All Artifact(s) types in a Drop"),
    url(r'^api/mediaArtifact/(?P<mediaArtifactName>.+)/version/(?P<mediaArtifactVersion>.+)/artifact/(?P<artifactName>.+)/KGBresults/$', GetMediaArtifactPackageRevKGB.as_view(), name="Frozen KGB Result for Artifact in Media Artifact Version Content"),
    url(r'^api/mediaArtifact/(?P<mediaArtifactName>.+)/version/(?P<mediaArtifactVersion>.+)/KGBresults/$', GetMediaArtifactPackageRevKGB.as_view(), name="Frozen KGB Results for Artifact(s) in Media Artifact Version Content"),
    url(r'^api/getteamfromjira/number/(?P<jira_num>.+)/$', GetTeamFromJira.as_view(), name="Get Team Name from Jira"),
    url(r'^api/artifact/(?P<artifact>.+)/version/(?P<version>.+)/nexusUrl/$', GetArtifactVersionFromNexus.as_view(), name="Getting Nexus Url for Given Artifact and Version"),
    url(r'^api/deliverAutoCreated/(?P<product>.+)/(?P<drop>.+)/$', DeliverAutoCreatedGroups.as_view()),
    url(r'^api/autoCreatedGroupDeliver/$', DeliverAutoCreatedGroup.as_view()),
    url(r'^api/productSet/list/$', GetAllProductSetNames.as_view()),
    url(r'^api/artifact/(?P<artifact>.+)/latestPassedKGB/$', GetLatestPassedKGBInfo.as_view()),
    url(r'^api/getProductwareToTestwareMediaMapping/product/(?P<product>.+)/drop/(?P<drop>.+)/mediaArtifact/(?P<mediaArtifactName>.+)/$', GetByDropProductwareToTestareMediaMapping.as_view(), name="Productware Media to Testware Media mapping in a Drop"),
    url(r'^api/getProductwareToTestwareMediaMapping/mediaArtifact/(?P<mediaArtifactName>.+)/version/(?P<mediaArtifactVersion>.+)/$', GetProductwareToTestwareMediaMapping.as_view(), name="Productware Media to Testware Media mapping"),
    url(r'^api/setMediaArtifactVersionInactive/mediaArtifact/(?P<mediaArtifactName>.+)/version/(?P<mediaArtifactVersion>.+)/$', SetMediaArtifactVersionInactive.as_view(), name="Setting a Artifact Version Inactive if not found in Nexus"),
    url(r'^api/setMediaArtifactVersionInactive/product/(?P<product>.+)/drop/(?P<drop>.+)/$', SetMediaArtifactVersInactiveByDrop.as_view(), name="Setting a Product Drop Artifact Versions Inactive in not found in Nexus"),
    url(r'^api/mediaArtifactVersionExternallyReleased/product/(?P<product>.+)/drop/(?P<drop>.+)/$', MediaArtifactVersionExternallyReleased.as_view(), name="Setting/Getting Media Artifact Version(s) Externally Released"),
    url(r'^api/getProductSetDropData/productSet/(?P<productSet>.+)/drop/(?P<drop>.+)/$', GetProductSetDropData.as_view(), name="Getting ProductSet Drop Data"),
    url(r'^api/getMediaArtifactVersionData/mediaArtifact/(?P<mediaArtifactName>.+)/version/(?P<mediaArtifactVersion>.+)/$', GetMediaArtifactVersionData.as_view(), name="Getting Media Artifact Version Data"),
    url(r'^api/getMediaSize/mediaArtifact/(?P<mediaArtifactName>.+)/version/(?P<mediaArtifactVersion>.+)/$', GetMediaArtifactDateAndSize.as_view(), name="Getting Media Artifact Size"),
    url(r'^api/product/(?P<product>.+)/latestdrop/$', GetLatestDropName.as_view(), name="Get Latest Drop Name"),
    url(r'^api/forceOption/(?P<forceOption>.+)/product/(?P<product>.+)/drop/(?P<drop>.+)/obsoleteGroup/(?P<groupId>.+)/$', ObsoleteGroupDeliveries.as_view()),
    url(r'^api/overrideConfidenceLevel/product/(?P<product>.+)/release/(?P<release>.+)/productSetVersion/(?P<productSetVersion>.+)/confidenceLevelType/(?P<confidenceLevelType>.+)$', OverrideConfidenceLevel.as_view()),
)

# cENM Routers
urlpatterns += patterns('cireports',
    url(r'^api/storeCNMetadata/$', storeCNMetadata.as_view()),
    url(r'^api/manageCNProductSet/(?P<productSetVersion>.+)/(?P<confidenceLevelName>.+)/(?P<pipelineStatus>.+)/$', ManageCNProductSet.as_view()),
    url(r'^api/cloudNative/dropsInProduct/.json/$', GetDropNamesForCloudNativeProduct.as_view()),
    url(r'^api/cenm/drop/(?P<dropName>.+)/productSetVersions/$', GetCNProductSetVersion.as_view()),
    url(r'^api/cloudNative/getLinkedCNProductSetVersion/(?P<enmProductSetVersion>.+)/$', GetLinkedCNProductSetVersion.as_view()),
    url(r'^api/cloudNative/getLinkedENMProductSetVersion/(?P<CNProductSetVersion>.+)/$', GetLinkedENMProductSetVersion.as_view()),
    url(r'^api/cloudNative/publishVerifiedCNContent/(?P<CNProductSetVersion>.+)/(?P<CNProductName>.+)/(?P<CNProductRevisionVersion>.+)/$', PublishVerifiedCNContent.as_view()),
    url(r'^api/cloudNative/unpublishVerifiedCNContent/(?P<CNProductSetVersion>.+)/(?P<CNProductName>.+)/(?P<CNProductRevisionVersion>.+)/$', UnPublishVerifiedCNContent.as_view()),
    url(r'^api/cloudnative/getCloudNativeProductSetContent/(?P<drop>.+)/(?P<productSetVersion>.+)/$', GetCloudNativeProductSetContent.as_view()),
    url(r'^cloudnative/historicalProductSetVersions/(\S+)/(\S+)/(\S+)/$', 'views.displayHistoricalCNProductSetVerions'),
    url(r'^cloudNative/createDeliveryGroup/(?P<product>.+)/(?P<drop>.+)/$', 'views.displayCNDeliveryGroupCreation'),
    url(r'^cloudNative/(?P<product>.+)/deliveryQueue/(?P<drop>.+)/(?P<dgNumber>.+)/$', 'views.displayCNDeliveryQueue', name='idCNDeliveryQueue'),
    url(r'^cloudNative/(?P<product>.+)/deliveryQueue/(?P<drop>.+)/$', 'views.displayCNDeliveryQueue', name='overviewCNQueue'),
    url(r'^cloudNative/deliveryQueue/editDeliveryGroup/(?P<deliveryGroupNumber>.+)/$', 'views.editDeliveryGroup'),
    url(r'^cloudNative/deliveryQueue/editJira/(?P<deliveryGroupNumber>.+)/$', 'views.editJira'),
    url(r'^cloudNative/deliveryQueue/addComment/(?P<product>.+)/(?P<drop>.+)/(?P<deliveryGroupNumber>.+)/(?P<deliveryGroupState>.+)/$', 'views.addCNDeliveryGroupComment'),
    url(r'^cloudNative/deliveryQueue/deliveryConfirmation/(?P<dropNumber>.+)/(?P<deliveryGroupNumber>.+)/$', 'views.displayCNDeliveryConfirmation'),
    url(r'^cloudNative/deliveryQueue/updateProductSetVersion/(?P<dropNumber>.+)/(?P<deliveryGroupNumber>.+)/$', 'views.displayProductSetVersionUpdate'),
    url(r'^cloudNative/deliveryQueue/addMissingDependenciesReason/(?P<dropNumber>.+)/(?P<deliveryGroupNumber>.+)/$', 'views.displayAddMissingDepReason'),
    url(r'^cloudnative/buildlog/(\S+)/$', 'views.getCNBuildLogData'),
    url(r'^cloudnative/buildlog/$', 'views.getLatestENMDrop'),
    url(r'^api/releaseISO/(?P<artifactName>.+)/$', ReleaseISOExternally.as_view()),
    url(r'^api/unreleaseISO/(?P<artifactName>.+)/$', UnreleaseISOExternally.as_view()),
    url(r'^api/getReleaseNote/(?P<productSetName>.+)/(?P<productSetVersion>.+)/$', GetReleaseNote.as_view()),
    url(r'^api/cloudNative/oldContentUpdate/updateOverallConfidenceLevel/$', UpdateOverallConfidenceLevel.as_view()),
    url(r'^api/cloudNative/overwriteOverallConfidenceLevel/(?P<productSetVersion>.+)/(?P<confidenceLevelState>.+)/$', OverwriteOverallConfidenceLevel.as_view()),
    url(r'^api/cloudNative/getGreenProductSetVersion/(?P<dropName>.+)/$', GetGreenProductSetVersion.as_view()),
    url(r'^api/cloudNative/postDeploymentUtilities/(?P<productSetVersion>.+)/$', PostDeploymentUtilities.as_view()),
    url(r'^api/getPackageProductMapping/packageName/(?P<packageName>.+)/$', GetPackageProductMapping.as_view()),
    url(r'^api/updateTeamInfo/$', UpdateTeamInfo.as_view()),
    url(r'^api/cloudNative/getOverallWorkingBaseline/drop/(?P<dropNumber>.+)/$', GetOverallWorkingBaseline.as_view()),
    url(r'^api/cloudNative/getConfidenceLevelVersion/$', GetConfidenceLevelVersion.as_view()),
    url(r'^api/cloudNative/updateCNProductSetVersionActiveness/user/(?P<userName>.+)/productSetVersion/(?P<productSetVersion>.+)/isActive/(?P<isActive>.+)/$', UpdateCNProductSetVersionActiveness.as_view()),
    url(r'^api/cloudNative/updateOldIntegrationValueFilesData/$', UpdateOldIntegrationValueFilesData.as_view()),
    url(r'^api/cloudNative/getActiveDropsByProduct/$', GetActiveDropsByProduct.as_view()),
    url(r'^api/cloudNative/getCNImage/$', GetCNImage.as_view()),
    url(r'^api/cloudNative/getCNProduct/(?P<productTypeName>.+)$', GetCNProduct.as_view()),
    url(r'^api/cloudNative/getDeliveryGroupsByDrop/(?P<queueType>.+)/$', GetDeliveryGroupsByDrop.as_view()),
    url(r'^api/cloudNative/(?P<productName>.+)/getCNDeliveryQueue/(?P<dropNumber>.+)/$', GetCNDeliveryQueue.as_view()),
    url(r'^api/cloudNative/deliveryQueue/deliverCNDeliveryGroup/$', DeliverCNDeliveryGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/obsoleteCNDeliveryGroup/(?P<deliveryGroupNumber>.+)/$', ObsoleteCNDeliveryGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/deleteCNDeliveryGroup/(?P<deliveryGroupNumber>.+)/$', DeleteCNDeliveryGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/restoreCNDeliveryGroup/(?P<deliveryGroupNumber>.+)/$', RestoreCNDeliveryGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/getServiceGroupInfo/(?P<deliveryGroupNumber>.+)/$', GetServiceGroupInfo.as_view()),
    url(r'^api/cloudNative/deliveryQueue/getIntegrationChartInfo/(?P<deliveryGroupNumber>.+)/$', GetIntegrationChartInfo.as_view()),
    url(r'^api/cloudNative/deliveryQueue/getIntegrationValueInfo/(?P<deliveryGroupNumber>.+)/$', GetIntegrationValueInfo.as_view()),
    url(r'^api/cloudNative/deliveryQueue/getPipelineInfo/(?P<deliveryGroupNumber>.+)/$', GetPipelineInfo.as_view()),
    url(r'^api/cloudNative/deliveryQueue/getImpactedDeliveryGroupInfo/(?P<deliveryGroupNumber>.+)/$', GetImpactedDeliveryGroupInfo.as_view()),
    url(r'^api/cloudNative/deliveryQueue/getJiraInfo/(?P<deliveryGroupNumber>.+)/$', GetJiraInfo.as_view()),
    url(r'^api/cloudNative/getCNDropByProductName/(?P<productName>.+)/$', GetCNDropByProductName.as_view()),
    url(r'^api/cloudNative/deliveryQueue/updateDeliveryGroupByCNProductSetVersion/$', UpdateCNDeliveryGroupByCNProductSetVersion.as_view()),
    url(r'^api/cloudNative/deliveryQueue/addCNDeliveryGroup/$', AddCNDeliveryGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/editIntegrationChart/(?P<deliveryGroupNumber>.+)/$', EditIntegrationChart.as_view()),
    url(r'^api/cloudNative/deliveryQueue/editIntegrationValue/(?P<deliveryGroupNumber>.+)/$', EditIntegrationValue.as_view()),
    url(r'^api/cloudNative/deliveryQueue/editPipeline/(?P<deliveryGroupNumber>.+)/$', EditPipeline.as_view()),
    url(r'^api/cloudNative/deliveryQueue/editImpactedDeliveryGroup/(?P<deliveryGroupNumber>.+)/$', EditImpactedDeliveryGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/editJira/(?P<deliveryGroupNumber>.+)/$', EditJira.as_view()),
    url(r'^api/cloudNative/deliveryQueue/editServiceGroup/(?P<deliveryGroupNumber>.+)/$', EditServiceGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/editCNDeliveryGroup/(?P<deliveryGroupNumber>.+)/$', EditCnDeliveryGroup.as_view()),
    url(r'^api/cloudNative/deliveryQueue/updateMissingDependencies/(?P<deliveryGroupNumber>.+)/$', UpdateMissingDependencies.as_view()),
    url(r'^api/cloudNative/deliveryQueue/getServiceGroupByGerritLink/$', GetServiceGroupByGerritLink.as_view()),
    url(r'^api/cloudNative/deliveryQueue/subscriptions/$', CnDeliveryGroupSubscription.as_view()),
    url(r'^api/cloudNative/getCNDgCreatedDetails/drop/(?P<dropNumber>.+)/$', GetCNDgCreatedDetails.as_view()),
    url(r'^api/cloudNative/getCNDgQueuedDetails/drop/(?P<dropNumber>.+)/$', GetCNDgQueuedDetails.as_view()),
    url(r'^api/cloudNative/updateOldDgDeliveredDate/$', UpdateOldDgDeliveredDate.as_view()),
    url(r'^api/cloudNative/getCNDgDeliveredDetails/drop/(?P<dropNumber>.+)/$', GetCNDgDeliveredDetails.as_view()),
    url(r'^api/cloudNative/updateCnProdRevDevLink/$', UpdateCnProdRevDevLink.as_view()),
    url(r'^api/cloudNative/updateCnImagesRepoName/$', UpdateCnImagesRepoName.as_view()),
    url(r'^api/cloudNative/updateOldDgObsoletedDate/$', UpdateOldDgObsoletedDate.as_view()),
    url(r'^api/cloudNative/updateOldDgDeletedDate/$', UpdateOldDgDeletedDate.as_view()),
    url(r'^api/cloudNative/getCNDgObsoletedDetails/drop/(?P<dropNumber>.+)/$', GetCNDgObsoletedDetails.as_view()),
    url(r'^api/cloudNative/getCNDgDeletedDetails/drop/(?P<dropNumber>.+)/$', GetCNDgDeletedDetails.as_view()),
    url(r'^api/cloudNative/addCNBuildLogData/$', AddCNBuildLogData.as_view()),
    url(r'^api/cloudNative/getCNBuildLogId/(?P<drop>.+)/(?P<toPs>.+)/(?P<confLevelName>.+)/(?P<deployment>.+)/$', GetCNBuildLogId.as_view()),
    url(r'^api/cloudNative/addCNBuildLogComment/$', AddCNBuildLogComment.as_view()),
    url(r'^api/cloudNative/editCNBuildLogComment/$', EditCNBuildLogComment.as_view()),
    url(r'^api/cloudNative/deleteCNBuildLogComment/$', DeleteCNBuildLogComment.as_view()),
    url(r'^api/cloudNative/deleteCNBuildLogJira/$', DeleteCNBuildLogJira.as_view()),
    url(r'^api/cloudNative/getCNBuildLogData/drop/(?P<drop>.+)/$', GetCNBuildLogData.as_view()),
    url(r'^api/cloudNative/updateCNBuildLogOverallStatus/$', UpdateCNBuildLogOverallStatus.as_view()),
    url(r'^api/cloudNative/jiravalidation/issue/(?P<number>.+)/$', CENMJIRAValidationViewSet.as_view()),
    url(r'^api/cloudNative/deleteCNBuildLog/$', HideCNBuildLog.as_view()),
)

urlpatterns += patterns('foss',
    (r'^foss/auditing/$', 'views.audit_repos'),
    url(r'^api/foss/auditing/user_name/(?P<user_name>.+)/bazaar_token/(?P<bazaar_token>.+)/bazaar_svl/(?P<bazaar_svl>.+)/$', SendForAuditing.as_view()),
)

urlpatterns += patterns('avs',
#    (r'^$', 'views.avs'),
#    (r'^avs/$', 'views.avs'),
    url(r'^avs/', include('avs.urls')),
)

urlpatterns += patterns('fem',
    (r'^femjob/$', 'views.femJob'),
    (r'^createfemjob/$', 'views.createFemJob'),
    (r'^getBuildStatus/$', 'views.getBuildStatus'),
    (r'^getPreviousEventIDs/$', 'views.getPreviousEventIDs'),
    url(r'^fem/', include('fem.urls')),
)

urlpatterns += patterns('virtual',
    (r'^createRepo/$', 'views.createRepo'),
    (r'^createAPTRepo/$', 'views.createAPTRepo'),
    (r'^deleteRepo/$', 'views.deleteRepo'),
    (r'^getImageCreationTemplate/$', 'views.restGetImageTemplates'),
     url(r'^api/createRHELPatchSetYumRepo/artifact/(?P<artifact>.+)/artifactVersion/(?P<artifactVersion>.+)/patchVersion/(?P<patchVersion>.+)/rhelVersion/(?P<rhelVersion>.+)/$', createRHELPatchSetYumRepo.as_view()),
     url(r'^api/createRHELPatchSetYumRepo/artifact/(?P<artifact>.+)/artifactVersion/(?P<artifactVersion>.+)/rhelVersion/(?P<rhelVersion>.+)/$', createRHELPatchSetYumRepo.as_view()),
     url(r'^api/createRHELPatchSetYumRepo/artifact/(?P<artifact>.+)/artifactVersion/(?P<artifactVersion>.+)/patchVersion/(?P<patchVersion>.+)/$', createRHELPatchSetYumRepo.as_view()),

     url(r'^api/createLatestYumRepoPath/product/(?P<product>.+)/yumRepo/(?P<yumRepo>.+)/$', createYumRepoLatestPath.as_view()),
)

urlpatterns += patterns('depmodel',
    (r'^(\S+)/dependencies/(\S+)/(\S+)/$', 'views.dependencyTree'),
    (r'^storedependency/(\S+)/(\S+)/$', 'views.storeDependencyRest'),
    (r'^returndependency/(\S+)/(\S+)/$', 'views.returnDependencyRest'),
    (r'^returncompletedependency/(\S+)/(\S+)/$', 'views.returnCompleteDependencyRest'),
    (r'^processArtifactsList/$','views.restProcessArtifactsList'),
    (r'^processReleaseTimeDependencies/$','views.restProcessReleaseTimeDependencies'),
    (r'^showPackageDependenciesMap/(\S+)/(\S+)/$', 'views.showPackageDependenciesMap'),
    (r'^showPackageCompleteDependenciesMap/(\S+)/(\S+)/$', 'views.showPackageCompleteDependenciesMap'),
    (r'^(\S+)/showDependencyStack/(\S+)/(\S+)/(\S+)/$', 'views.showDependencyStack'),
    (r'^(\S+)/showPackageDependenciesStackISO/(\S+)/(\S+)/(\S+)/$', 'views.showPackageDependenciesStackISO'),
    url(r'^api/product/(?P<product>.+)/isoname/(?P<isoname>.+)/isoversion/(?P<isoversion>.+)/applications/modules/', ProductISOVersionApplicationsModules.as_view(), name="productISOVersionApplicationsModulesView"),
    url(r'^api/anomalyName/(?P<anomalyName>.+)/anomalyGroupId/(?P<anomalyGroupId>.+)/anomalyVersion/(?P<anomalyVersion>.+)/anomalyPackaging/(?P<anomalyPackaging>.+)/', GetAnomalyMatch.as_view(), name="getAnomalyMatchApplicationsModulesView"),
    url(r'^api/processAnomalies/$', ProcessAnomalies.as_view()),
    url(r'^api/processAnomalyPackageRevisionMapping/$', ProcessAnomalyPackageRevisionMapping.as_view()),
    url(r'^api/processVersionMismatches', ProcessVersionMismatches.as_view()),
    url(r'^api/createPackageArtifactMapping/', CreatePackageArtifactMapping.as_view()),
)

urlpatterns += patterns('cpi',
    (r'^(\S+)/cpibuilds/(\S+)/$', 'views.displayCPIBuilds'),
    (r'^(\S+)/cpiDocs/(\S+)/(\S+)/$', 'views.displayCPIDocumentIndex'),
    (r'^(\S+)/cpiDocList/(\S+)/(\S+)/$', 'views.displayCPIDocuments'),
    (r'^(\S+)/addCPIDocument/(\S+)/(\S+)/$', 'views.addCPIDocument'),
    (r'^(\S+)/editCPIDocument/(\S+)/(\S+)/(\S+)/$', 'views.editCPIDocument'),
    (r'^(\S+)/batchimport/(\S+)/(\S+)/$','views.CPIFromExcel'),
    (r'^(\S+)/searchcpi/(\S+)/(\S+)/$','views.searchCPIDocument'),
    (r'^(\S+)/buildstatus/(\S+)/(\S+)/$','views.displayStatus'),
    (r'^(\S+)/cpibuild/(\S+)/(\S+)/$','views.initiateCPIbuild'),
    (r'^(\S+)/downloadexcel/(\S+)/(\S+)/$','views.downloadExcel'),
    (r'^(\S+)/downloadsdi/(\S+)/(\S+)/$','views.downloadSDI'),
    (r'^(\S+)/logindwaxe/(\S+)/(\S+)/(\S+)/$','views.loginDwaxe'),
)


urlpatterns += patterns('vis',
    (r'^vis/showWidgets/$', 'views.showWidgets'),
    (r'^vis/addWidget/$', 'views.addWidget'),
    (r'^vis/editWidget/(\S+)/$', 'views.editWidget'),
    (r'^vis/deleteWidget/(\S+)/$', 'views.deleteWidget'),
    (r'^vis/showWidgetDefinitions/(.*)/$', 'views.showWidgetDefintions'),
    (r'^vis/showWidgetDefinitions/$', 'views.showWidgetDefintions'),
    (r'^vis/addWidgetDefinition/(\S+)/$', 'views.addWidgetDefinition'),
    (r'^vis/editWidgetDefinition/(\S+)/$', 'views.editWidgetDefinition'),
    (r'^vis/deleteWidgetDefinition/(\S+)/$', 'views.deleteWidgetDefinition'),
    (r'^vis/showWidgetRender/$', 'views.showWidgetRender'),
    (r'^vis/WidgetRenders/(\S+)/(\S+)/(.*)/$', 'views.WidgetRenders'),
    (r'^vis/WidgetRenders/(\S+)/(\S+)/$', 'views.WidgetRenders'),
    (r'^vis/deletetWidgetRender/(\S+)/$', 'views.deleteWidgetRender'),
    (r'^vis/showWidgetMappings/$', 'views.showWidgetRenderToDefinitionsMappping'),
    (r'^vis/showChartMappings/$', 'views.showChartMapping'),
    (r'^vis/showChartMappings/(.*)/$', 'views.showChartMapping'),
    (r'^vis/editMapping/(\S+)/$', 'views.editMapping'),
    (r'^vis/deleteMapping/(\S+)/(\S+)/$', 'views.deleteMapping'),
    (r'^vis/(.*)/api/json/$', 'views.radiatorCustomViewJson'),
    (r'^vis/(.*)/$', 'views.radiatorCustomView'),
  #  (r'^radiator/(\S+)$', 'views.getRadiatorInfo'),
)

urlpatterns += patterns('dmt',
    (r'^dmt/log/(\S+)/(\S+)/$', 'views.changeLog'),
    (r'^dmt/log/(\S+)/$', 'views.changeLog'),
    (r'^dmt/deploycluster/(\S+)/$', 'views.deployCluster'),
    (r'^dmt/sshkey/', 'views.sshKey'),
    (r'^dmt/editserver/(\S+)/(\S+)/(\S+)', 'views.updateClusterServer'),
    (r'^dmt/deleteserver/(\S+)/(\S+)/$', 'views.deleteClusterServer'),
    (r'^dmt/editDeploymentStatus/(\S+)/(\S+)/(\S+)', 'views.editDeploymentStatus'),
    (r'^dmt/editDeploymentStatus/(\S+)/(\S+)', 'views.editDeploymentStatus'),
    (r'^deploymentStatus/', 'views.deploymentStatus'),
    (r'^dmt/editmgtsvr/(\S+)/$', 'views.updateMgtServer'),
    (r'^dmt/deletemgtsvr/(\S+)/$', 'views.deleteMgtServer'),
    (r'^dmt/editnassvr/(\S+)/(\S+)/$', 'views.updateNASServer'),
    (r'^dmt/deletenassvr/(\S+)/(\S+)/$', 'views.updateNASServer'),
    (r'^dmt/editcluster/(\S+)/(\S+)/$', 'views.updateCluster'),
    (r'^dmt/deletecluster/(\S+)/(\S+)/$', 'views.updateCluster'),
    (r'^dmt/editmcast/(\S+)/(\S+)/$', 'views.updateMulticast'),
    (r'^dmt/appTemplate/$', 'views.appTemplates'),
    (r'^dmt/mgtsvrs/$', 'views.showMgtServers'),
    (r'^dmt/nassvrs/$', 'views.showNASServers'),
    (r'^dmt/$', 'views.showMgtServers'),
    (r'^dmt/mgtsvrs/(\S+)/$', 'views.showMgtServers'),
    (r'^dmt/nassvrs/(\S+)/$', 'views.showNASServers'),
    (r'^dmt/clusters/$', 'views.showClusters'),
    (r'^dmt/clusters/(\d+)/$', 'views.showClusters'),
    (r'^dmt/clusters/(\S+)/(details)/$', 'views.showClusters'),
    (r'^dmt/addmgtsvr/(\S+)/(\S+)/$', 'views.productType'),
    (r'^dmt/addmgtsvr/(\S+)$', 'views.addMgtServer'),
    (r'^dmt/addsvr/$', 'views.addServer'),
    (r'^dmt/updatedhcplifetime/(\S+)/$', 'views.updateDHCPLifetime'),
    (r'^dmt/addsvr/(\S+)/(\S+)/(\S+)/$', 'views.addServer'),
    (r'^dmt/addsvr/(\S+)/(\S+)$', 'views.addServer'),
    (r'^dmt/addcluster/$', 'views.addCluster'),
    (r'^dmt/changeClusterGroupOnCluster/(\S+)/$', 'views.changeClusterGroupOnCluster'),
    (r'^dmt/changeClusterGroup/$', 'views.changeClusterGroup'),
    (r'^dmt/attachClsServer/(\S+)/(\S+)/(\S+)/$', 'views.attachClusterServer'),
    (r'^dmt/attachClsServer/(\S+)/(\S+)/$', 'views.attachClusterServer'),
    (r'^dmt/addclustersvr/(\S+)/(\S+)/(\S+)/$', 'views.addClusterServer'),
    (r'^dmt/addcluster/(\S+)/mcasts$', 'views.addMulticasts'),
    (r'^dmt/deletemcast/(\S+)/$', 'views.deleteMulticasts'),
    (r'^dmt/addcluster/(\S+)/(\S+)/addServiceGroup/$', 'views.addServiceGroup'),
    (r'^dmt/addcluster/(\S+)/addServicesCluster/$', 'views.addServicesCluster'),
    (r'^dmt/addveritas/(\S+)/vcs/$', 'views.addVeritasCluster'),
    (r'^dmt/(\S+)/startapp$', 'views.startApp'),
    (r'^dmt/(\S+)/LITP_(\S+)/$', 'views.AppHost'),
    (r'^dmt/updateveritas/(\S+)/vcs/$', 'views.updateVeriatasClusterDetails'),
    (r'^dmt/deleteveritascluster/(\S+)/$', 'views.deleteVeritasCluster'),
    (r'^dmt/editServiceGroup/(\S+)/(\S+)/$', 'views.updateServiceGroup'),
    (r'^dmt/deleteServiceGroup/(\S+)/(\S+)/$', 'views.deleteServiceGroup'),
    (r'^dmt/addServiceGroupCredentials/(\S+)/(\S+)/$', 'views.addServiceGroupCredentials'),
    (r'^dmt/updateServiceGroupCredentials/(\S+)/(\S+)/$', 'views.updateServiceGroupCredentials'),
    (r'^dmt/deleteServiceGroupCredentials/(\S+)/(\S+)/$', 'views.deleteServiceGroupCredentials'),
    (r'^dmt/editServiceGroupInstance/(\S+)/(\S+)/$', 'views.updateServiceGroupInstance'),
    (r'^dmt/editInternalServiceGroupInstance/(\S+)/(\S+)/$', 'views.updateInternalServiceGroupInstance'),
    (r'^dmt/deleteServiceGroupInstance/(\S+)/(\S+)/$', 'views.deleteServiceGroupInstance'),
    (r'^dmt/deleteInternalServiceGroupInstance/(\S+)/(\S+)/$', 'views.deleteInternalServiceGroupInstance'),
    (r'^dmt/deleteServicesCluster/(\S+)/(\S+)/$', 'views.deleteServicesCluster'),
    (r'^dmt/mgtsvr/(\S+)/delete/credential/(\S+)/$', 'views.deleteMgmtServerCredentials'),
    (r'^dmt/mgtsvr/(\S+)/(\S+)/credential/(\S+)/$', 'views.updateMgmtServerCredentials'),
    (r'^dmt/mgtsvr/(\S+)/(\S+)/credential/$', 'views.updateMgmtServerCredentials'),
    (r'^dmt/(\S+)/server/(\S+)/(\S+)/(\S+)/delete/credential/(\S+)/$', 'views.deleteServerCredentials'),
    (r'^dmt/(\S+)/server/(\S+)/(\S+)/(\S+)/(\S+)/credential/(\S+)/$', 'views.updateServerCredentials'),
    (r'^dmt/(\S+)/server/(\S+)/(\S+)/(\S+)/(\S+)/credential/$', 'views.updateServerCredentials'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/(\S+)/delete/credential/(\S+)/$', 'views.deleteVirtualImageCredentials'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/(\S+)/(\S+)/credential/(\S+)/$', 'views.virtualImageCredentials'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/(\S+)/(\S+)/credential/$', 'views.virtualImageCredentials'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.virtualImageIpInfo'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.virtualImageIpInfo'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/delete/(\S+)/$', 'views.deleteVirtualImageIpInfo'),
    (r'^dmt/delete/virtualImage/(\S+)/(\S+)/$', 'views.deleteVirtualImage'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/(\S+)/$', 'views.virtualImage'),
    (r'^dmt/(\S+)/virtualImage/(\S+)/$', 'views.virtualImage'),
    (r'^dmt/(\S+)/multicast/(\S+)/(\S+)/$', 'views.clusterMulticasts'),
    (r'^dmt/(\S+)/multicast/(\S+)/$', 'views.deleteClusterMulticasts'),
    (r'^dmt/(\S+)/databaseVip/(\S+)/$', 'views.databaseVip'),
    (r'^dmt/(\S+)/deleteDatabaseVip/(\S+)/$', 'views.deleteDatabaseVip'),
    # service group id
    (r'^dmt/serviceGroup/(\S+)/addPackage/$', 'views.addPackageToServiceGroup'),
    # cluster id, service group id
    (r'^dmt/(\S+)/serviceGroup/(\S+)/addInstance', 'views.addServiceGroupInstance'),
    (r'^dmt/(\S+)/serviceGroup/(\S+)/addInternalInstance', 'views.addInternalServiceGroupInstance'),
    (r'^dmt/(\S+)/nasStorage/details/Tor/$', 'views.addNasStorageDetailsTor'),
    (r'^dmt/(\S+)/nasStorage/details/OSS/$', 'views.addNasStorageDetailsOSS'),
    (r'^dmt/deleteSGPackages/(\S+)/', 'views.deletedPackageFromServiceGroup'),
    (r'^dmt/editSGPackages/(\S+)/', 'views.updatePackageToServiceGroup'),
    (r'^dmt/clusterBuildArtifact/(\S+)/$', 'views.buildClusterArtifact'),
    (r'^dmt/addJbossCluster/(\S+)/$', 'views.addJbossCluster'),
    (r'^dmt/addStorage/$', 'views.addStorageDetails'),
    (r'^dmt/deleteStorage/(\S+)/(\S+)/$', 'views.updateStorageServer'),
    (r'^dmt/editStorage/(\S+)/(\S+)/$', 'views.updateStorageServer'),
    (r'^dmt/storage/(\S+)/$', 'views.showStorageServers'),
    (r'^dmt/storage/$', 'views.showStorageServers'),
    (r'^dmt/addEnclosure/$', 'views.addEnclosureDetails'),
    (r'^dmt/deleteEnclosure/(\S+)/(\S+)/$', 'views.updateEnclosureServer'),
    (r'^dmt/editEnclosure/(\S+)/(\S+)/$', 'views.updateEnclosureServer'),
    (r'^dmt/enclosure/(\S+)/$', 'views.showEnclosureServers'),
    (r'^dmt/enclosure/$', 'views.showEnclosureServers'),
    (r'^dmt/addSAN/(\S+)/$', 'views.addStorageAttachedNetwork'),
    (r'^dmt/addDAS/(\S+)/SAN/$', 'views.addDirectAttachedStorageSAN'),
    (r'^dmt/addDAS/(\S+)/NAS/$', 'views.addDirectAttachedStorageNAS'),
    (r'^dmt/(\S+)/extraNasStorage/details/$', 'views.addExtraNasStorageDetails'),
    (r'^dmt/addDAS/(\S+)/$', 'views.dasType'),
    (r'^dmt/addOSSRC/(\S+)/$', 'views.addOSSRCCluster'),
    (r'^dmt/vlan/(\S+)/(\S+)/$', 'views.vlanDetails'),
    (r'^dmt/deleteHBVlan/(\S+)/$', 'views.deleteHBVlan'),
    (r'^dmt/virtualConnect/(\S+)/(\S+)/$', 'views.virtualConnectNetworks'),
    (r'^dmt/addSSO/(\S+)/$', 'views.addSsoInfo'),
    (r'^dmt/edit/ssodetails/(\S+)/$', 'views.editSsoInfo'),
    (r'^dmt/delete/ssodetails/(\S+)/$', 'views.deleteSsoInfo'),
    (r'^dmt/editdas/nas/(\S+)/$', 'views.editDirectAttachedStorageNas'),
    (r'^dmt/editdas/(\S+)/$', 'views.editDirectAttachedStorageSan'),
    (r'^dmt/deletedas/nas/(\S+)/$', 'views.deleteDirectAttachedStorageNas'),
    (r'^dmt/deletedas/(\S+)/$', 'views.deleteDirectAttachedStorageSan'),
    (r'^dmt/editSanTor/(\S+)/$', 'views.editStorageAttachedNetworkTor'),
    (r'^dmt/editSanOSS/(\S+)/$', 'views.editStorageAttachedNetworkOSS'),
    (r'^dmt/editOProps/(\S+)/(\S+)/$', 'views.editClusterOtherProperties'),
    (r'^dmt/dvmsInformation/(\S+)/(\S+)/$', 'views.dvmsInformation'),
    (r'^dmt/deletesan/(\S+)/$', 'views.deleteStorageAttachedNetwork'),
    (r'^dmt/edit/tor2ossrc/(\S+)/$','views.editTorToOSSRCCluster'),
    (r'^dmt/delete/tor2ossrc/(\S+)/$','views.deleteTorToOSSRCCluster'),
    (r'^dmt/getHostProperties/(\S+)/$', 'views.getHostProperties'),
    (r'^generateTAFHostProperties/$', 'views.generateTAFHostProperties'),
    (r'^getMasterSedVersion/$', 'views.getMasterSedVersion'),
    (r'^getDeployScriptVersion/$', 'views.getDeployScriptMapping'),
    (r'^dmt/getLatestPackageObj/$','views.getPackageInfo'),
    (r'^dmt/editSED/(\S+)/$','views.editSED'),
    (r'^dmt/UploadSED/$','views.uploadSed'),
    (r'^dmt/ViewUploadSED/$','views.viewUploadSed'),
    (r'^dmt/ViewUploadSED/(\S+)/$','views.viewUploadSed'),
    (r'^generateTAFHostPropertiesJSON/$', 'views.generateTAFHostPropertiesJSON'),
    (r'^dmt/MapVirtSED/(\S+)/$', 'views.mapVirtualSed'),
    (r'^dmt/searchInventory/$', 'views.searchInventory'),
    (r'^dmt/generateSED/$', 'views.generateSED'),
    (r'^dmt/(\S+)/dataLocation/$', 'views.dataBaseLocation'),
    (r'^dmt/upload/preLoadedSed/$', 'views.upload_file'),
    (r'^dmt/(\S+)/deployment/execute/$', 'views.executePopulateOrVerifyDeployment'),
    (r'^dmt/(\S+)/deployment/(\S+)/$', 'views.populateOrVerifyDeployment'),
    (r'^dmt/(\S+)/deployment/$', 'views.populateOrVerifyDeployment'),
    (r'^dmt/searchInstallGroup/dashboard/(\S+)/$', 'views.searchInstallGroup'),
    (r'^dmt/searchInstallGroup/$', 'views.searchInstallGroup'),
    (r'^dmt/deleteInstallGroup/(\S+)/$', 'views.installGroupDelete'),
    (r'^dmt/deleteInstallGroupDeployment/(\S+)/(\S+)/$', 'views.installGroupDeploymentDelete'),
    (r'^dmt/installGroupDeployment/(\S+)/(\S+)/$', 'views.installGroupDeployments'),
    (r'^dmt/(\S+)/vlanMulticast/(\S+)/$', 'views.vlanMulticast'),
    (r'^dmt/(\S+)/vlanClusterMulticast/(\S+)/$', 'views.vlanClusterMulticast'),
    (r'^dmt/installGroup/(\S+)/(\S+)/$', 'views.installGroup'),
    (r'^dmt/uploadSnapshot/$','views.uploadSnapshotRpm'),
    (r'^dmt/uploadSnapshotRest/$','views.uploadSnapshotRpmRest'),
    (r'^dmt/displayDeploymentData/$','views.displayDeploymentData'),
    (r'^dmt/deployment/(\S+)/service/ip/range/(\S+)/(\S+)/$','views.serviceIpRange'),
    (r'^dmt/(\S+)/lvsrouterVip/(\S+)/$', 'views.lvsRouterVip'),
    (r'^dmt/(\S+)/hybridCloud/(\S+)/$', 'views.hybridCloud'),
    (r'^dmt/(\S+)/deploymentDescription/(\S+)/$', 'views.deploymentDescriptionDeploymentMapping'),
    (r'^dmt/deploymentsSummaryReports/$','views.deploymentsUpdatedSummaryReports'),
    (r'^dmt/deploymentsUpdatedReport/(\S+)/$','views.deploymentsUpdatedReport'),
    (r'^dmt/deploymentUpdatedReport/(\S+)/$','views.deploymentUpdatedReport'),
    (r'^dmt/deploymentArtifactsInstalled/$','views.deploymentArtifactsInstalledAudit'),
    (r'^dmt/(\S+)/editDatabaseProvider/$', 'views.deploymentDatabaseProvider'),
    (r'^api/deployment/lms/pw/(?P<signum>.+)/(?P<lmsHostname>.+)/(?P<user>.+)/$', LMSPassword.as_view()),
    (r'^api/deployment/lms/pw/$', LMSPassword.as_view()),
    (r'^api/deployment/manageDeploymentServer/clusterId/(?P<clusterId>.+)/$', ManageDeploymentServer.as_view()),
    (r'^api/deployment/clusters/(?P<deploymentId>.[0-9]+)/$', IndividualClusterViewSet.as_view({'get':'list'})),
    (r'^api/deployment/testresults/date/(?P<date>.+)/group/(?P<group>.+)/$', MapTestResultsToDeploymentFilterViewSet.as_view({'get':'list'})),
    (r'^api/deployment/testresults/date/(?P<date>.+)/$', MapTestResultsToDeploymentFilterViewSet.as_view({'get':'list'})),
    (r'^api/deployment/testgroups/default/(?P<default>.+)/$', TestGroupFilterViewSet.as_view({'get':'list'})),
    (r'^api/deployment/(?P<id>.+)/status/$', DeploymentStatusViewSet.as_view()),
    (r'^api/deployment/installGroup/status/failedsettoidle/$', InstallGroupFailedDeploymentsCheckViewSet.as_view()),
    url(r'^api/deployment/info/(?P<product>.+)/(?P<productType>.+)/(?P<productDrop>.+)/(?P<version>.+)/$', GetDeploymentInformation.as_view(), name="getDeploymentInformation"),
    url(r'^api/deployment/info/(?P<product>.+)/(?P<productType>.+)/(?P<productDrop>.+)/$', GetDeploymentInformation.as_view(), name="getDeploymentInformation"),
    url(r'^api/deployment/installGroup/(?P<installGroup>.+)/getIdleCluster/', GetFreeClusterFromGroupAndSetStatus.as_view(), name="getFreeClusterFromInstallGetAndSetStatus"),
    url(r'^api/deployment/(?P<deploymentId>.[0-9]+)/sed/(?P<sedVersion>.+)/generate/', GeneratedSedFile.as_view(), name="GeneratedSedFile"),
    url(r'^api/deployment/(?P<deploymentId>.[0-9]+)/vm/service/ip/range/data/(?P<typeId>.+)/$', GetServiceVMIpRanges.as_view({'get':'list'})),
    url(r'^api/deployment/(?P<deploymentId>.[0-9]+)/vm/service/dns/ip/range/data/(?P<typeId>.+)/$', GetServiceVMDnsIpRanges.as_view({'get':'list'})),
    url(r'^api/deployment/allIps/$', GetAllDmtIps.as_view({'get':'list'})),
    url(r'^api/deployment/(?P<deploymentId>.[0-9]+)/vm/service/data/all/$', GetServiceInfo.as_view({'get':'list'})),
    url(r'^api/deployment/sed/template/(?P<sedVersion>.+)/download/', DownloadSedTemplate.as_view(), name="DownloadSedTemplate"),
    url(r'^api/deployment/range/items/$', GetServiceVMIpRangeItems.as_view({'get':'list'})),
    url(r'^api/deployment/searchdeployment/(?P<valueEntered>.+)/',SearchDeploymentInventory.as_view(), name="searchDeploymentInventory"),
    url(r'^api/deployment/verify/(?P<deploymentId>.[0-9]+)/sedVersion/(?P<sedVersion>.+)/$', executeVerifyOfDeploymentViewSet.as_view(), name="executeVerifyOfDeploymentViewSet"),
    url(r'^api/clusterServer/(?P<clusterServer>.+)/clusterServerId/(?P<clusterServerId>.[0-9]+)/activeStatus/(?P<activeStatus>.+)/(?P<action>.+)/$', login_required(UpdateClusterServerActiveStatus.as_view())),
    url(r'^api/deployment/validate/autodeploy/artifacts/(?P<artifacts>.+)/$', ValidateAutoDeployPackages.as_view(), name="validateDeployPackagesViewSet"),
    url(r'^api/deployment/deploymentutilities/product/(?P<product>.+)/isobuildversion/(?P<isoBuildVersion>.+)/utilities/(?P<utilityData>.+)/$',DeploymentUtilities.as_view(), name="deploymentUtilities"),
    url(r'^api/deployment/deploymentutilities/productSet/(?P<productSet>.+)/version/(?P<productSetVersion>.+)/mediaArtifact/(?P<mediaArtifact>.+)/$', GetDeploymentUtilitiesWithProductSetVersion.as_view()),
    url(r'^api/deployment/deploymentutilities/productSet/(?P<productSet>.+)/version/(?P<productSetVersion>.+)/$', GetDeploymentUtilitiesWithProductSetVersion.as_view()),
    url(r'^api/deployment/deploymentutilities/productSet/(?P<productSet>.+)/mediaArtifact/(?P<mediaArtifact>.+)/$', GetDeploymentUtilitiesWithProductSetVersion.as_view()),
    url(r'^api/deployment/deploymentutilities/productSet/(?P<productSet>.+)/$', GetDeploymentUtilitiesWithProductSetVersion.as_view()),
    url(r'^api/deployment/getlatestartifactversion/$',GetLatestVersion.as_view()),
    url(r'^api/deployment/installGroup/$',GetInstallGroup.as_view()),
    url(r'^api/deployment/deploymentTemplates/productSet/(?P<productSet>.+)/version/(?P<productSetVersion>.+)/$', GetDeploymentTemplatesVersionWithProductSetVersion.as_view()),
    url(r'^api/deployment/deploymentTemplates/productSet/(?P<productSet>.+)/$', GetDeploymentTemplatesVersionWithProductSetVersion.as_view()),
    url(r'^api/deployment/updateDeploymentDescriptionData/version/(?P<version>.+)/$', UpdateDeploymentDescriptions.as_view()),
    url(r'^api/deployment/updateClustersServicesWithDD/$', UpdateClustersServicesWithDD.as_view()),
    url(r'^api/deployment/updateClustersServicesWithDD/(?P<clusterId>.+)/$', UpdateClustersServicesWithDD.as_view()),
    url(r'^api/setDeploymentServersStatus/$', SetDeploymentServersStatus.as_view()),
    url(r'^api/deployment/deploymentDescriptions/version/(?P<version>.+)/type/(?P<ddType>.+)/capacityType/(?P<capacityType>.+)/$', GetDeploymentDescriptions.as_view()),
    url(r'^api/deployment/deploymentDescriptions/version/(?P<version>.+)/type/(?P<ddType>.+)/$', GetDeploymentDescriptions.as_view()),
    url(r'^api/deployment/updateClusterIPRanges/$', UpdateClusterIPRanges.as_view()),
    url(r'^api/deployment/updateClusterIPRanges/(?P<clusterId>.+)/$', UpdateClusterIPRanges.as_view()),
    url(r'^api/deployment/deploymentDescription/(?P<clusterId>.+)/$', GetDeploymentDD.as_view(), name="Deployment's Deployment Description Data"),
    url(r'^api/deployment/updateDeploymentDescription/(?P<clusterId>.+)/(?P<ddName>.+)/$', UpdateDeploymentDD.as_view(), name="Deployment's Deployment Description Data"),
    url(r'^api/deployment/getClusterAdditionalProperties/clusterId/(?P<clusterId>.+)/$', GetClusterAdditionalProperties.as_view()),
    url(r'^api/deployment/updateClusterAdditionalProperties/clusterId/(?P<clusterId>.+)/$', UpdateClusterAdditionalProperties.as_view()),
    url(r'^api/deployment/getNasDetails/(?P<input>.+)/$', GetNasDetails.as_view()),
)

urlpatterns += patterns('fwk',
    (r'^fwk/createChangeLog/$', 'views.createCL'),
    (r'^fwk/changeLog/$', 'views.changeLog'),
    (r'^fwk/links/$', 'views.displayTeams'),
    (r'^fwk/links/(\S+)/$', 'views.displayLinks'),
    (r'^fwk/summary/(\S+)/$', 'views.displaySummary'),
    (r'^fwk/rest/summaryurls/(\S+)/$', 'views.displaySummaryUrls'),
    (r'^fwk/rest/summary/(\S+)/$', 'views.displaySummaryUrls'),
    (r'^fwk/devServers/$', 'views.registerDevelopmentServer'),
    (r'^fwk/devServers/list/$', 'views.showDevelopmentServer'),
    (r'^fwk/editdevserver/(\S+)/(\S+)', 'views.updateDevelopmentServer'),
    (r'^fwk/deletedevserver/(\S+)/(\S+)', 'views.updateDevelopmentServer'),
    (r'^getver/$', 'views.getVer'),
    (r'^getlatestbuild/$', 'views.getLatestBuild'),
    (r'^glossary/$', 'views.showGlossaryItems'),
    (r'^TickerTapeHistory/$', 'views.showTickerTapeHistory'),
    (r'^preRegisterArtifact/$', 'views.preRegisterArtifact'),
    # Comment out for now (Ability to Upgrade the CI Framework via web interface)
    #(r'^upgrade/$', 'views.ugForm'),
    #(r'^admin/upgrade/$', 'views.upgrade'),
)

urlpatterns += patterns('metrics',
    (r'^metrics/CloudMetrics/$', 'views.viewCloudMetrics'),
    (r'^metrics/GetEventList/$', 'views.getEventData'),
    (r'^metrics/kgbmetrics/$', 'views.KGBPackageInformation'),
    (r'^metricdata/$', 'views.showMetricsData'),
    (r'^metrics/KgbMetrics/$', 'views.viewKgbMetrics'),
    (r'^metrics/showKgbMetricData/$', 'views.showKgbMetricsTable'),
    (r'^metrics/allProducts/.json/$', 'views.getProductsJson'),
    (r'^metrics/AllPackages/.json/$', 'views.allPackagesJson'),
    (r'^metrics/AllComponents/.json/$', 'views.allComponentsJson'),
    (r'^metrics/AllLabels/.json/$', 'views.allLabelsJson'),
    (r'^metrics/GetComponentsFromProducts/$', 'views.getComponentsFromProducts'),
    (r'^metrics/GetPackagesFromComponent/$', 'views.getPackagesFromComponents'),
    (r'^downloadKGBMetricsFile/$', 'views.downloadKGBMetricsFile'),
    (r'^downloadMetricsFile/$', 'views.downloadMetricsFile'),
    (r'^dropsInProduct/.json/$', 'views.getDropNamesForProduct'),
    (r'^revisionsReleasedInDrop/.json/$', 'views.getRevisionsReleasedForDrop'),
)


urlpatterns += patterns('excellence',
    (r'^excellence/showQuestions/$', 'views.showQuestions'),
    (r'^excellence/addQuestion/$', 'views.addQuestion'),
    (r'^excellence/showCategories/$', 'views.showCategory'),
    (r'^excellence/addCategory/$', 'views.addCategory'),
    (r'^excellence/showOrganisations/$', 'views.showOrganistaion'),
    (r'^excellence/addOrganisation/$', 'views.addOrganistaion'),
    (r'^excellence/takeQuestionnaire/$', 'views.takeQuestionnaire'),
    (r'^excellence/questionnaire/(\S+)/(\S+)/(\S+)/(\S+)/$', 'views.questionnaireContinued'),
    (r'^excellence/searchQuestionnaires/$', 'views.searchQuestionnaires'),
    (r'^excellence/questionnaire/(\S+)/$', 'views.showPastResults'),
)

urlpatterns += patterns('cloud',
    (r'^mapGatewayToSpp/$', 'views.mapGatewayToSpp'),
    (r'^getSpp/$', 'views.getSpp'),
)

urlpatterns += patterns('visualisation',
    (r'^visualisation/baseline/$', getLatestENMDrop),
    (r'^visualisation/baseline/(\S+)/$', login_required(BaselineView.as_view())),
    (r'^visualisation/baseline/(\S+)/(\S+)/$', login_required(BaselineView.as_view())),
    (r'^visualisation/serverutilization/$', ServerUtilizationView.as_view()),
)

urlpatterns += patterns('fastcommit',
    (r'^dockerimages/$', 'views.display_docker_images'),
    (r'^dockerimages/(\S+)/$', 'views.display_docker_image_versions'),
)

urlpatterns += patterns('',
    # Examples:
    # url(r'^$', 'django_proj.views.home', name='home'),
    # url(r'^django_proj/', include('django_proj.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^rest/doc/', include('rest_framework_swagger.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
)

urlpatterns += [
    url(r'^api/', include(router.urls)),
    url(r'^api/', include(simple_router.urls)),
    url(r'^api/deploymentbaseline/drop/(?P<dropName>.+)/$', DeploymentBaselineDropViewSet.as_view({'get':'list'})),
    url(r'^api/deploymentbaseline/dropgroup/(?P<dropName>.+)/(?P<groupName>.+)/$', DeploymentBaselineDropGroupViewSet.as_view({'get':'list'})),
    url(r'^api/deploymentbaseline/dropmaster/(?P<dropName>.+)/$', DeploymentBaselineDropMasterViewSet.as_view({'get':'list'})),
    url(r'^api/deployment/clustertogroup/$', DeploymentToInstallViewSet.as_view({'get':'list'})),
    url(r'^api/deployment/clustertogroup/(?P<cluster>.+)/$', DeploymentToInstallClusterNameViewSet.as_view({'get':'list'})),
    url(r'^api/cireports/component/(?P<product>.+)/(?P<label>.+)/$', ComponentProductViewSet.as_view({'get':'list'})),
    url(r'^api/cireports/component/(?P<product>.+)/$', ComponentProductViewSet.as_view({'get':'list'})),
    url(r'^api/cireports/team/(?P<package>.+)/$', PackageComponentViewSet.as_view({'get':'list'})),
    url(r'^api/cireports/component/$', ComponentViewSet.as_view({'get':'list'})),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/tools/jiravalidation/issue/(?P<number>.+)/$', JIRAValidationViewSet.as_view()),
    url(r'^api/tools/updatejiradata/product/(?P<product>.+)/drop/(?P<drop>.+)/$', UpdateJiraData.as_view()),
    url(r'^api/tools/updatejiradata/product/(?P<product>.+)/$', UpdateJiraData.as_view()),
    url(r'^api/tools/updatejiradata/$', UpdateJiraData.as_view()),
    url(r'^api/tools/grouppackageversionvalidation/(?P<product>.+)/(?P<drop>.+)/(?P<groupId>.+)/$', GroupPackageVersionValidationViewSet.as_view()),
    url(r'^api/tools/packageversionvalidation/(?P<product>.+)/(?P<drop>.+)/(?P<package>.+)/(?P<version>.+)/$', PackageVersionValidationViewSet.as_view()),
    url(r'^api/tools/packageversionvalidation/(?P<product>.+)/(?P<drop>.+)/(?P<package>.+)/(?P<version>.+)/(?P<groupId>.+)$', PackageVersionValidationViewSet.as_view()),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
