#!/bin/bash
tail=/usr/bin/tail
awk=/bin/awk

area=$1
requiredMinSpace=$2

spaceLeft=$(df -k ${area} | ${tail} -1 | ${awk} '{print $3}')
hostName=$( hostname )

spaceLeftHuman=$( echo ${spaceLeft} | awk '{ split( "KB MB GB" , v ); s=1; while( $1>1024 ){ $1/=1024; s++ } print int($1) v[s] }')
requiredMinSpaceHuman=$( echo ${requiredMinSpace} | awk '{ split( "KB MB GB" , v ); s=1; while( $1>1024 ){ $1/=1024; s++ } print int($1) v[s] }')

if ((${spaceLeft} < ${requiredMinSpace}));then
    mail -s "Warning Space on ${hostName} is getting low" "PDLCIAXISC@ericsson.com" <<EOF
The space for the specified directory (${area}) is getting low.

It has less than the minimum space specified, ${requiredMinSpaceHuman}

Currently the space for ${area} is ${spaceLeftHuman}

Please Investigate
EOF
fi
