#!/bin/bash -a

sudo /usr/bin/oz-customize -d3 __TEMPLATEDESCRIPTION__  __TEMPLATEKVMDESCRIPTION__ -c /etc/oz/oz.cfg
if [ $? -ne 0 ] ; then
    exit $?
fi
export TMPDIR=/dev/shm/
if [ $? -ne 0 ] ; then
    exit $?
fi
/usr/bin/virt-sparsify --compress __IMAGELOCATION__ __COMPRESSEDIMAGELOCATION__ 
if [ $? -ne 0 ] ; then
    exit $?
fi
